# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5413e9aee92cb496f56d2da6ec58cb30c3b3f99e594581344bff1c7d389a1aa00c9264c8ad652aa4d9d0aee1a01d8115ddf68e7a5246a6f5c1db7bb00e944c4f

test:
  secret_key_base: 05fc26507d9ce854328afe38644143e779b20697cf79620b8079f46b8716edb31bbdfc84b63ad57ee015c1f82dfcd8076c8732a4634675aaa1633e0aff70739f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4fdc5875cb9ae088de22a115e90a9f50a44d9e43f2d1c64c9126e8a615a3bbcc655fe1b6e1e01b9580aae8a1aed69888a4a44258678cb2abe4970b00f2b29418
